#!/bin/bash

# USAGE !
# $cattemp {contest_name}

contest_name=$1
for alpha in {a,b,c,d,e,f}
do
    cp mytemplate/ContestTemplate.cpp ${contest_name}_${alpha}.cpp
    File=${contest_name}_${alpha}.cpp
    sed -i -e "s|__PROBLEM__|$contest_name Big_Alpha|g" ${File}
    
    big=$(echo "$alpha" | tr a-z A-Z )
    sed -i -e "s|Big_Alpha|$big|g" ${File}
    ptime=`date '+%Y/%m/%d'`
    sed -i -e "s|__MAKE_TIME__|$ptime|g" ${File}
done

