#!/bin/bash

# USAGE !
# yuki 123 => yukicoder123.cpp

in_number=$1

cp mytemplate/ContestTemplate.cpp yukicoder${in_number}.cpp
File=yukicoder${in_number}.cpp
    
sed -i -e "s|__CONTEST_URL__|http://yukicoder.me/problems/no/__CONTEST_NUMBER__|g" ${File}
sed -i -e "s|__PROBLEM__|yukicoder __CONTEST_NUMBER__ |g" ${File}
sed -i -e "s|__CONTEST_NUMBER__|$in_number|g" ${File}

ptime=`date '+%Y/%m/%d'`
sed -i -e "s|__MAKE_TIME__|$ptime|g" ${File}
